#define ansi_background_black "\x1b[40m"
#define ansi_background_blue "\x1b[44m"
#define ansi_background_cyan "\x1b[46m"
#define ansi_background_default "\x1b[49m"
#define ansi_background_green "\x1b[42m"
#define ansi_background_magenta "\x1b[45m"
#define ansi_background_red "\x1b[41m"
#define ansi_background_rgb( r, g, b ) "\x1b[48;2;" r ";" g ";" b "m"
#define ansi_background_white "\x1b[47m"
#define ansi_background_yellow "\x1b[43m"
#define ansi_blinking_end "\x1b[25m"
#define ansi_blinking_start "\x1b[5m"
#define ansi_bold_end "\x1b[22m"
#define ansi_bold_start "\x1b[1m"
#define ansi_cursor_hidden "\x1b[?25l"
#define ansi_cursor_home "\x1b[H"
#define ansi_cursor_show "\x1b[?25h"
#define ansi_dim_end "\x1b[22m"
#define ansi_dim_start "\x1b[2m"
#define ansi_end_alt_screen "\x1b[?1049l"
#define ansi_erase_cursor_to_end "\x1b[0J"
#define ansi_erase_cursor_to_end_line "\x1b[0K"
#define ansi_erase_cursor_to_start "\x1b[1J"
#define ansi_erase_cursor_to_start_line "\x1b[1K"
#define ansi_erase_line "\x1b[2K"
#define ansi_erase_saved_lines "\x1b[3J"
#define ansi_erase_screen "\x1b[2J"
#define ansi_foreground_black "\x1b[30m"
#define ansi_foreground_blue "\x1b[34m"
#define ansi_foreground_cyan "\x1b[36m"
#define ansi_foreground_default "\x1b[39m"
#define ansi_foreground_green "\x1b[32m"
#define ansi_foreground_magenta "\x1b[35m"
#define ansi_foreground_red "\x1b[31m"
#define ansi_foreground_rgb( r, g, b ) "\x1b[38;2;" r ";" g ";" b "m"
#define ansi_foreground_white "\x1b[37m"
#define ansi_foreground_yellow "\x1b[33m"
#define ansi_inverse_end "\x1b[27m"
#define ansi_inverse_start "\x1b[7m"
#define ansi_invisible_end "\x1b[28m"
#define ansi_invisible_start "\x1b[8m"
#define ansi_italic_end "\x1b[23m"
#define ansi_italic_start "\x1b[3m"
#define ansi_move_column( count ) "\x1b[" count "G"
#define ansi_move_down( count ) "\x1b[" count "B"
#define ansi_move_left( count ) "\x1b[" count "D"
#define ansi_move_line_start_down( count ) "\x1b[" count "F"
#define ansi_move_line_start_up( count ) "\x1b[" count "E"
#define ansi_move_line_up_scroll "\x1b M"
#define ansi_move_rigth( count ) "\x1b[" count "C"
#define ansi_move_to_line_column( line, column ) "\x1b[" line ";" column "H"
#define ansi_move_up( count ) "\x1b[" count "A"
#define ansi_request_cursor_possition "\x1b[6n"
#define ansi_reset_graphics "\x1b[0m"
#define ansi_restore_cursor_position "\x1b 8"
#define ansi_restore_screen "\x1b[?47l"
#define ansi_save_cursor_position "\x1b 7"
#define ansi_save_screen "\x1b[?47h"
#define ansi_start_alt_screen "\x1b[?1049h"
#define ansi_strikethrough_end "\x1b[29m"
#define ansi_strikethrough_start "\x1b[9m"
#define ansi_underline_end "\x1b[24m"
#define ansi_underline_start "\x1b[4m"
