
"\x0"  key_control_2 
"\x0"  key_control_space 
"\x1"  key_control_a 
"\x10"  key_control_p 
"\x11"  key_control_q 
"\x12"  key_control_r 
"\x13"  key_control_s 
"\x14"  key_control_t 
"\x15"  key_control_u 
"\x16"  key_control_v 
"\x17"  key_control_w 
"\x18"  key_control_x 
"\x19"  key_control_y 
"\x1a"  key_control_z 
"\x1b "  key_alt_space 
"\x1b!"  key_alt_exclamation_point 
"\x1b"  key_control_3 
"\x1b"  key_control_open_bracket 
"\x1b"  key_escape 
"\x1b#"  key_alt_hashtag 
"\x1b$"  key_alt_dollar 
"\x1b%"  key_alt_percent 
"\x1b&"  key_alt_ampersand 
"\x1b'"  key_alt_single_quote 
"\x1b("  key_alt_open_parenthesis 
"\x1b)"  key_alt_close_parenthesis 
"\x1b*"  key_alt_star 
"\x1b+"  key_alt_plus 
"\x1b,"  key_alt_comma 
"\x1b-"  key_alt_dash 
"\x1b."  key_alt_period 
"\x1b/"  key_alt_slash 
"\x1b0"  key_alt_0 
"\x1b1"  key_alt_1 
"\x1b2"  key_alt_2 
"\x1b3"  key_alt_3 
"\x1b4"  key_alt_4 
"\x1b5"  key_alt_5 
"\x1b6"  key_alt_6 
"\x1b7"  key_alt_7 
"\x1b8"  key_alt_8 
"\x1b9"  key_alt_9 
"\x1b:"  key_alt_colon 
"\x1b;"  key_alt_semi_colon 
"\x1b<"  key_alt_less_then 
"\x1b="  key_alt_equals 
"\x1b>"  key_alt_greater_then 
"\x1b?"  key_alt_question_mark 
"\x1b@"  key_alt_at 
"\x1bA"  key_alt_A 
"\x1bB"  key_alt_B 
"\x1bC"  key_alt_C 
"\x1bD"  key_alt_D 
"\x1bE"  key_alt_E 
"\x1bF"  key_alt_F 
"\x1bG"  key_alt_G 
"\x1bH"  key_alt_H 
"\x1bI"  key_alt_I 
"\x1bJ"  key_alt_J 
"\x1bK"  key_alt_K 
"\x1bL"  key_alt_L 
"\x1bM"  key_alt_M 
"\x1bN"  key_alt_N 
"\x1bO"  key_alt_O 
"\x1bP"  key_alt_P 
"\x1bQ"  key_alt_Q 
"\x1bR"  key_alt_R 
"\x1bS"  key_alt_S 
"\x1bT"  key_alt_T 
"\x1bU"  key_alt_U 
"\x1bV"  key_alt_V 
"\x1bW"  key_alt_W 
"\x1bX"  key_alt_X 
"\x1bY"  key_alt_Y 
"\x1bZ"  key_alt_Z 
"\x1b["  key_alt_open_bracket 
"\x1b[1;2A"  key_shift_up_arrow 
"\x1b[1;2B"  key_shift_down_arrow 
"\x1b[1;2C"  key_shift_right_arrow 
"\x1b[1;2D"  key_shift_left_arrow 
"\x1b[1;2F"  key_shift_end 
"\x1b[1;2H"  key_shift_home 
"\x1b[1;3A"  key_alt_up_arrow 
"\x1b[1;3B"  key_alt_down_arrow 
"\x1b[1;3C"  key_alt_right_arrow 
"\x1b[1;3D"  key_alt_left_arrow 
"\x1b[1;3F"  key_alt_end 
"\x1b[1;3H"  key_alt_home 
"\x1b[1;4A"  key_shift_alt_up_arrow 
"\x1b[1;4B"  key_shift_alt_down_arrow 
"\x1b[1;4C"  key_shift_alt_right_arrow 
"\x1b[1;4D"  key_shift_alt_left_arrow 
"\x1b[1;4F"  key_shift_alt_end 
"\x1b[1;4H"  key_shift_alt_home 
"\x1b[1;5A"  key_control_up_arrow 
"\x1b[1;5B"  key_control_down_arrow 
"\x1b[1;5C"  key_control_right_arrow 
"\x1b[1;5D"  key_control_left_arrow 
"\x1b[1;5F"  key_control_end 
"\x1b[1;5H"  key_control_home 
"\x1b[1;6A"  key_control_shift_up_arrow 
"\x1b[1;6B"  key_control_shift_down_arrow 
"\x1b[1;6C"  key_control_shift_right_arrow 
"\x1b[1;6D"  key_control_shift_left_arrow 
"\x1b[1;6F"  key_control_shift_end 
"\x1b[1;6H"  key_control_shift_home 
"\x1b[1;7A"  key_control_alt_up_arrow 
"\x1b[1;7B"  key_control_alt_down_arrow 
"\x1b[1;7C"  key_control_alt_right_arrow 
"\x1b[1;7D"  key_control_alt_left_arrow 
"\x1b[1;7F"  key_control_alt_end 
"\x1b[1;7H"  key_control_alt_home 
"\x1b[1;8A"  key_control_shift_alt_up_arrow 
"\x1b[1;8B"  key_control_shift_alt_down_arrow 
"\x1b[1;8C"  key_control_shift_alt_right_arrow 
"\x1b[1;8D"  key_control_shift_alt_left_arrow 
"\x1b[1;8F"  key_control_shift_alt_end 
"\x1b[1;8H"  key_control_shift_alt_home 
"\x1b[3;2~"  key_shift_delete 
"\x1b[3;3~"  key_alt_delete 
"\x1b[3;4~"  key_shift_alt_delete 
"\x1b[3;5~"  key_control_delete 
"\x1b[3;6~"  key_control_shift_delete 
"\x1b[3;7~"  key_control_alt_delete 
"\x1b[3;8~"  key_control_shift_alt_delete 
"\x1b[3~"  key_delete 
"\x1b[5;2~"  key_shift_page_up 
"\x1b[5;3~"  key_alt_page_up 
"\x1b[5;4~"  key_shift_alt_page_up 
"\x1b[5;5~"  key_control_page_up 
"\x1b[5;6~"  key_control_shift_page_up 
"\x1b[5;7~"  key_control_alt_page_up 
"\x1b[5;8~"  key_control_shift_alt_page_up 
"\x1b[5~"  key_page_up 
"\x1b[6;2~"  key_shift_page_down 
"\x1b[6;3~"  key_alt_page_down 
"\x1b[6;4~"  key_shift_alt_page_down 
"\x1b[6;5~"  key_control_page_down 
"\x1b[6;6~"  key_control_shift_page_down 
"\x1b[6;7~"  key_control_alt_page_down 
"\x1b[6;8~"  key_control_shift_alt_page_down 
"\x1b[6~"  key_page_down 
"\x1b[A"  key_up_arrow 
"\x1b[B"  key_down_arrow 
"\x1b[C"  key_right_arrow 
"\x1b[D"  key_left_arrow 
"\x1b[F"  key_end 
"\x1b[H"  key_home 
"\x1b\""  key_alt_double_quote 
"\x1b\\"  key_alt_backslash 
"\x1b\x0"  key_control_alt_space 
"\x1b\x1b"  key_alt_escape 
"\x1b\x1b"  key_control_alt_3 
"\x1b\x1b"  key_control_alt_open_bracket 
"\x1b\x1c"  key_control_alt_4 
"\x1b\x1c"  key_control_alt_backslash 
"\x1b\x1d"  key_control_alt_5 
"\x1b\x1d"  key_control_alt_close_bracket 
"\x1b\x1e"  key_control_alt_6 
"\x1b\x1f"  key_control_alt_7 
"\x1b\x1f"  key_control_alt_underscore 
"\x1b\x7f"  key_alt_back_space 
"\x1b\x7f"  key_control_alt_8 
"\x1b\x8"  key_control_alt_backspace 
"\x1b\x9"  key_alt_tab 
"\x1b\xa"  key_alt_enter 
"\x1b]"  key_alt_close_bracked 
"\x1b^"  key_alt_caret 
"\x1b_"  key_alt_underscore 
"\x1ba"  key_alt_a 
"\x1bb"  key_alt_b 
"\x1bc"  key_alt_c 
"\x1bd"  key_alt_d 
"\x1be"  key_alt_e 
"\x1bf"  key_alt_f 
"\x1bg"  key_alt_g 
"\x1bh"  key_alt_h 
"\x1bi"  key_alt_i 
"\x1bj"  key_alt_j 
"\x1bk"  key_alt_k 
"\x1bl"  key_alt_l 
"\x1bm"  key_alt_m 
"\x1bn"  key_alt_n 
"\x1bo"  key_alt_o 
"\x1bp"  key_alt_p 
"\x1bq"  key_alt_q 
"\x1br"  key_alt_r 
"\x1bs"  key_alt_s 
"\x1bt"  key_alt_t 
"\x1bu"  key_alt_u 
"\x1bv"  key_alt_v 
"\x1bw"  key_alt_w 
"\x1bx"  key_alt_x 
"\x1by"  key_alt_y 
"\x1bz"  key_alt_z 
"\x1b{"  key_alt_open_curly_bracket 
"\x1b|"  key_alt_pipe 
"\x1b}"  key_alt_closed_curly_bracket 
"\x1c"  key_control_4 
"\x1c"  key_control_backslash 
"\x1d"  key_control_5 
"\x1d"  key_control_close_bracket 
"\x1e"  key_control_6 
"\x1e"  key_control_caret 
"\x1f"  key_control_7 
"\x1f"  key_control_underscore 
"\x2"  key_control_b 
"\x3"  key_control_c 
"\x4"  key_control_d 
"\x5"  key_control_e 
"\x6"  key_control_f 
"\x7"  key_control_g 
"\x7f"  key_backspace 
"\x8"  key_control_backspace 
"\x8"  key_control_h 
"\x9"  key_control_i 
"\x9"  key_tab 
"\xa"  key_control_j 
"\xa"  key_control_m 
"\xa"  key_enter 
"\xb"  key_control_k 
"\xc"  key_control_l 
"\xe"  key_control_n 
"\xf"  key_control_o 
